name: Test on Chrome

on: [push]

env:
  GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
  NODE_OPTIONS: "--max-old-space-size=8192"

jobs:
  chrome:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.21.0]

    steps:
      - uses: actions/checkout@v2

      - name: Setup kernel for React, increase watchers
        run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://npm.pkg.github.com
          always-auth: true

      - name: Use Yarn cache
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn install --prefer-offline --frozen-lockfile

      - name: Generate GraphQL files
        run: yarn relay

      - name: Run tests on Chrome
        run: yarn test:coverage --browsers=ChromeHeadless --single-run --no-auto-watch

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
